apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCSckG7Xhf33prlPOm1Z5Hev4b5/Nbo+QamN9kv2yVhN/7JVn4PqAq79d70i5rsDrhXvwL4PJyo+8BghU0cCNfsNj5DHX2vfHkS4ezohV/BbKL8kqmHwambSR3y766fexSZ3yUZVz80hV//s5YwPiRR98kLDgvBqq4A4KkEgpax5f0Oal2Aa/qXs6wQxGLarJylFzURzp96bQrLfDaxgKUVCZgTwJS/ffCZSqrYExDbVuHMbBlfwfmUI6tEgQxkeuuWcqA0ycw106RwT6NXuZhDXz21lS/KKt9JeDDVKbkSu20h5DpZ0fI2ZETd5hz0JdjRKHLZseuzlj7IsiPV/O88i96vjW2W5o0SND0yXgDkf3oB4R/KpidEjWn1nSVQVhwjC68Cio3UwaSBrdBwYRG0roiauBiintpMUWPz1O9woSOTC33YVDFzXs7eVe9BRRBjSprXhWzigB/SH5UDZ/Ops5/HW3IHGWHnsdvbv49JIrjSnLD/ua8b5FODRN7tZvTBlrkJUsIbtsSrvDZz/ps7pPa7YEUpLPVIwZjW9Sb3ty92PUhqkFr1TEJGc4CiG59xuNbopwS6diG9q9G82v4S4o+GcNK9hAWTcSgliAfKMpzQPdU02KW988ANTuT5G6U46N+QoHofE7AyPuRGRBUT/4je1uFZ+FEgfYOrDVc3dGYewiTrsJAbR+y7OrU0Cq8HHNLq6q5ufjClGqLfMnFdyHzSbJmHPIEnYdO/S3S/S1O7YI5RxkE6Ru41hBmYrsCslOPVU4hHF21eulBNUh8qTLJjRWduKIORbo4kzokqCR+Bzf06lQ1O12aHRnMNnNfkNdH5t9uDnFuJxAEOloX6adyPvAwPCbH7rtsrDgq0qqhznq/v216EH/JrwJASil8UcOzKR4WowNXBCnyHAdEdUJEw/wW0Rx+VchAbVM+NmUfPXZXSlMuUpC4ULUTL4ccznKv0vCLIJMJ7hC4uqxv+QrIDSKtd8nExPNrXiUG8sIwqmoQFvZOz9xT43c4CuQKbQkQQ/Lc+NWi82L0/jj/JWlG5SoqsKBlCuHfO0/7G0MymtGRzYeuINuaRIqdO4vHEZVyoDRV4GHJxEQaKqrfffYrF+KWxcFEcnYfo+RMaNHJbdSuv8L/DiRRK8VvQmaT5AqImY9MYtvZ0y8vWHfBly2MgLal6ATyXb3VdKx7Q7ahFx7f6/es14CaCBJsQePMUW6Wb+wNvmxlE+6UGp8t5rzCtlNsjmHBD1YwLsyaQhQ==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
