apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgAgj3wbG5AYJxACFtuWcxZZGetag9O8SQMrYHfUxHa8TJeTjCpQD6Gz0rRU7mdJ7tRwyW7oZJdHXS8kEclxoraBskS+RPznZk7eT3rkMx2XlQLml3du9oxk6TlgSV0mKnTz9nYgDRf9F56XoKbul7nhdr7T+W8LfjWHyB1t6qwsEl09ssJg9mn7erylUQ8Mef42kpkbMaXYRsnE2XMG7ZrMzZXCFa0z7/nKnNcmZ3FRUXZvuUrtlwSMSYCzf94EtwZl0XlLZkittSrja42KUXNE77rl34sp4TihLXnzJPpnk8p6UqtMBpdHgF0YEo491ktGVGCAMyKtK7GsSOM0lf/hcOUVsX4cTLDcr5qMaM1UIbjxes1dq1Pf9tIuMsdkblwQuABYZUrS5kYtV/ZlfdXB01QozIbk38aDo4Ga/dKCd2YOibiZIrO0SwW0ajgXQY9LuLUCKM5Eyk39JX3ekNqo87Tecu07kqnikEzyE0rSJgWdinYkFDuo+g7lFKVLPcTWe5kgUAOOYd3oUjXu7le8s4/GUtBVEFK+Ak3xjSJQ1RJppIYQ4fREJfVzS388nVkA1B+kzlFPxQ6C5jwGSMVsHmX1iVtRxHYNxXbh+bDduPkd4zwfAwmwxDc7kJroThH0OMJgQWAyP8TOWNka699qPO7wXXA8Jjcm6u/MUqt8Z579LR9WSQlRbgmJkaxIGqd34URbpq7D8yIRluQG2N9idbHJ9RDYIajRni4fMYFC2YouTjGetgyz
    username: AgCPGtd6sZxS6i5+tGEJVuFLIt050EfrkPPk2H4fzb2CPKH8cNhWc+ii4rF1aUsJk8CSMlTK5spnGLKZnyfVK86yGFdpsaBAyk3vUbFThD0h7AIOQecJ9ktyAIS+iHUjuo4LS56oOgAeNxC/yGC/oBNrrLCrTgm3hCWdyWTdgwHUe3tBCWZa6/+HaUdB24iO9AnUKBi5TqR3OWCplaTXDwcCyEhqe+6g50g0bnxqVugNxybsXrU6hSPkjyVnp4n90LqcBwHpFwcK6M6TapgDyszFFrCqpNfNgBEA7zrQCRLqtBCvf5i4KWi0XghxXlxpe7CY0llhx4Axs0rgeUdteC+eGD+KPt+50Xd33DDOBETE/0M58AEOMlIHUrj5kQvBJIYFdc3fVcI3uFXPBAPB6bt22+ErXXPVV7hcBU+3ddv4TeUvLP4QEeQS9gEXDQO5Kov6E2pLYAE7oSsSdSXC6dcWQdlHwhIninUv9+UpTnya9NA89+SzKdZ0spmjynNvdtGF7s6dknnNWQbSG+GTvPX2b0sWvKeIbKphtu2hjmVaV1X+Qk4NXn9cD2Gk9dBabI4r6FtWYyaxOGKczy7S3S8dNl05TR9c0Vm35dbn2aGmrNuKYKBSIsMql1/wDqIX8eoggLN3lGCkLwdy4T4HoE01srJB0v8W8EmSBKhFvJbI/xta8T4P3OK6fatXaPl0o2wfWa+YUzs=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
