apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAx9M4umUOOMjzvAcXT2eoUCjfkLpzZfmp1GlC86FxLQCMfxXxWqryFWkKqTYY374JVGOHB7nb9qDNJca3broA+44WMOVLM/A6WDxbnrGT9vHsf7ZXVB0qc0QMkuJqkKtzxlTrT3AvjDFEjtdjJopjnoXVFeW3K5AQE/hT1JpP5ThNXsWF1rQbkPMENcl1IcvOAwDZySChyFM/vZYoqCU7bbgHPXx9XTG5RvhC7KTElymVuKdZF/rj9aVEoahxzPty9b8N0GrucSRzTM6P6aXDcxPtoe5w2Wnd9kZQHfzywLWS2sac+maW7h1EhhSEpLWXHVO7ULATgM46SLomMQi813jUuQCzLNqVeayMAWBDiTzFisZJA+qC7RTf/WXd6u/M9tYjReegNyFjHp2R63fAXgAJVtGv319D3/SzXR37GilnW3loB6eq6r33gTr9zd8YXZZZ9hSiJyWCvaxJiBN6GItdrSzJULdkxaYzZlfwvi98PrNKa68RCDrqIxTj5J/M6vx7nEw3rkIQVnRr0E+2GPNpOYDJnHJp9f6dciM+NXldOioP5qXBULQ8J3Cb6NfAA+6Je4TFzaD5AhxmAC2RscupQ4jqWJLecFNnupxOy7vMUwk1Gn180Ac4XIW5y7OUss7Nix8pAgH+kl4dwgTa5yVjjqVzo7tICt22wjb76piP/6KmEs2eViRq8iJdoKw8sYJRQt22+tu+4tAV4g5mnD7gzyg==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
