apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgA8uoYhSmFIK9Y+07hmuJi6rjD8ar4yBUiKSozB6NcCXMkykg0XJEkbH8rZ/eV/FP/eE3sETAqSWuziUXWAewTtPFaDbZBCwkXvUKPZFGwdlHUnEcFVQdavwG+S7SSnpUEVXwOvG5B7spc2KyajG/TZB+ANTJ9I52CxmgFgcu6O6Tp58SEAy3P5FNNWhc2Vphi9ai2CyUZF7+sYG8uLxoiI2rqo5LQnkJkXTPEx+itWWpIdM7ffPu0fKTC7erWaQ6bBICCcgDvsPhPnYrZCVexNXZ6dNMWg0ISBa2LQR1jpJT1leU0IPl7+v8pYI0Hk5QAbeH/KToiQL502PPKsVZ6R1YhA0IKl+Y2tMKwLLN0lkcuZU3ar8UNJk6YhZ9cvDlC9NmYeupV08gTT7I5rYZ8nnIO/4jePWoAt7ooRV1OYWftFoVXXr8n/cLjCzKD0ZvASiMUTqO3J8U1W2YNAraBxLBND2mntp0BtLHRYEBj48YjcUAEOdrcPpxMzy/WQ+C2wlplijMb9No8LhU36KZBynn5UQ3cDj8aN5il3K2FiZYmq/VcAzMvLXAqoNSD6ijdIu4C76ilijSpUGggvMOWvfj6MoiTErIArBDlQcc9LCWXk4x47/o1hY/dlAJR5xNa+jWutAD80pOqxqeuLyT+Rd/YXEOQ35vsgsRUROO1vkv5CjzyhrkONVsrUtXLKhVEuv+Dv1DxWNwXGPCcrl2oaPMh5+w==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
